<a href="https://colab.research.google.com/github/Ebasurtos/clase1-progrmacion101/blob/main/BASURTO_SIUCE%2C_Eder_EXAMEN_3_(Programaci%C3%B3n_01).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PREGUNTA 1:**

 a) Crea un array unidimensional que contenga los números primos entre 1 y 50.



In [27]:
def es_primo(n):

  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True

primos = []
for i in range(2, 51):
  if es_primo(i):
    primos.append(i)

primos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]

b) Convierte el array unidimensional anterior en una matriz de forma (n, 2), donde n es el número adecuado de
 filas. Si es necesario, agrega ceros al final del array para completar la matriz.

In [29]:
import numpy as np

n = len(primos)
n_filas = (n + 1) // 2

matriz_primos = np.zeros((n_filas, 2), dtype=int)

for i in range(n_filas):
  matriz_primos[i, 0] = primos[2*i] if 2*i < n else 0
  matriz_primos[i, 1] = primos[2*i + 1] if 2*i + 1 < n else 0

matriz_primos

array([[ 2,  3],
       [ 5,  7],
       [11, 13],
       [17, 19],
       [23, 29],
       [31, 37],
       [41, 43],
       [47,  0]])

 c) Calcula la suma de cada fila y crea un nuevo array que contenga estos valores.

In [28]:
suma_filas = np.sum(matriz_primos, axis=1)
suma_filas

array([ 5, 12, 24, 36, 52, 68, 84, 47])

**PREGUNTA 2:**

 a) Crea un array bidimensional de forma (4, 4) que contenga números enteros aleatorios entre 1 y 100.

In [30]:
array_2d = np.random.randint(1, 101, size=(4, 4))
array_2d

array([[43,  8, 98, 61],
       [46, 66, 39, 66],
       [19, 25, 79, 42],
       [97,  1, 51, 18]])

b) Cambia el tipo de datos del array a float64 y divide todos los elementos por 3.7.

In [31]:
array_2d = array_2d.astype(np.float64) / 3.7
array_2d

array([[11.62162162,  2.16216216, 26.48648649, 16.48648649],
       [12.43243243, 17.83783784, 10.54054054, 17.83783784],
       [ 5.13513514,  6.75675676, 21.35135135, 11.35135135],
       [26.21621622,  0.27027027, 13.78378378,  4.86486486]])

 c) Calcula y muestra las siguientes propiedades del array resultante:

 ● Dimensiones (ndim)

 ● Forma(shape)

 ● Tamañototal (size)

 ● Tipodedatos (dtype)

In [32]:
print("Dimensiones:", array_2d.ndim)
print("Forma:", array_2d.shape)
print("Tamaño total:", array_2d.size)
print("Tipo de datos:", array_2d.dtype)

Dimensiones: 2
Forma: (4, 4)
Tamaño total: 16
Tipo de datos: float64


**PREGUNTA 3:**

 a) Crea un array x que contenga 100 valores equiespaciados entre-10 y 10.

In [33]:
x = np.linspace(-10, 10, 100)
x

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

b) Calcula el valor de la función f(x)=e**(-x**2) para cada elemento de x.

In [34]:
import math

funcion_x = np.exp(-x**2)
funcion_x

array([3.72007598e-44, 2.03026390e-42, 1.02118442e-40, 4.73376699e-39,
       2.02236984e-37, 7.96279046e-36, 2.88948872e-34, 9.66335032e-33,
       2.97841666e-31, 8.46046409e-30, 2.21489900e-28, 5.34397817e-27,
       1.18830091e-25, 2.43522554e-24, 4.59941880e-23, 8.00603952e-22,
       1.28435035e-20, 1.89889213e-19, 2.58742690e-18, 3.24927813e-17,
       3.76059612e-16, 4.01122945e-15, 3.94320471e-14, 3.57249927e-13,
       2.98295005e-12, 2.29546576e-11, 1.62797100e-10, 1.06407812e-09,
       6.40990174e-09, 3.55860870e-08, 1.82079103e-07, 8.58600196e-07,
       3.73140910e-06, 1.49453385e-05, 5.51683065e-05, 1.87682835e-04,
       5.88451217e-04, 1.70038545e-03, 4.52830117e-03, 1.11140983e-02,
       2.51399360e-02, 5.24089078e-02, 1.00692485e-01, 1.78295348e-01,
       2.90960459e-01, 4.37601640e-01, 6.06561603e-01, 7.74857597e-01,
       9.12262625e-01, 9.89848834e-01, 9.89848834e-01, 9.12262625e-01,
       7.74857597e-01, 6.06561603e-01, 4.37601640e-01, 2.90960459e-01,
      

 c) Encuentra el valor máximo y mínimo de f(x) y las posiciones en el array donde ocurren.

In [35]:
valor_maximo = np.max(funcion_x)
posicion_maximo = np.argmax(funcion_x)
valor_minimo = np.min(funcion_x)
posicion_minimo = np.argmin(funcion_x)

print("Valor máximo de f(x):", valor_maximo)
print("Posición del valor máximo:", posicion_maximo)
print("Valor mínimo de f(x):", valor_minimo)
print("Posición del valor mínimo:", posicion_minimo)

Valor máximo de f(x): 0.9898488339361309
Posición del valor máximo: 49
Valor mínimo de f(x): 3.720075976020836e-44
Posición del valor mínimo: 0


PREGUNTA 4:

 Dado el siguiente array bidimensional:
 array = np.arange(1, 101).reshape(10, 10)

 a) Extrae un subarray que contenga los elementos en posiciones pares de filas y columnas (es decir, filas y
 columnas con índices 0, 2, 4, 6, 8).

In [36]:
array = np.arange(1, 101).reshape(10, 10)
sub_array = array[::2, ::2]
sub_array

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29],
       [41, 43, 45, 47, 49],
       [61, 63, 65, 67, 69],
       [81, 83, 85, 87, 89]])

 b) Reemplaza todos los elementos que son múltiplos de 3 por-1.

In [37]:
sub_array[sub_array % 3 == 0] = -1
sub_array

array([[ 1, -1,  5,  7, -1],
       [-1, 23, 25, -1, 29],
       [41, 43, -1, 47, 49],
       [61, -1, 65, 67, -1],
       [-1, 83, 85, -1, 89]])

c) Utiliza indexación avanzada para extraer todos los números primos del array original y crea un nuevo array
 con estos valores.

In [38]:
primos_array = array[np.vectorize(es_primo)(array)]
primos_array

array([ 2,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61,
       67, 71, 73, 79, 83, 89, 97])

PREGUNTA 5:

 a) Crea tres arrays unidimensionales de longitud 5 con números aleatorios entre 0 y 1.

In [39]:
array1 = np.random.rand(5)
array2 = np.random.rand(5)
array3 = np.random.rand(5)

print("Array 1:", array1)
print("Array 2:", array2)
print("Array 3:", array3)

Array 1: [0.88617047 0.07307434 0.53782684 0.57827093 0.4967988 ]
Array 2: [0.72953104 0.41609104 0.68834974 0.97768604 0.34469846]
Array 3: [0.25841717 0.81347171 0.68264449 0.50589128 0.59174938]


 b) Combina estos arrays para formar una matriz de forma (5, 3).

In [40]:
matriz_combinada = np.column_stack((array1, array2, array3))
print("Matriz combinada:\n", matriz_combinada)

Matriz combinada:
 [[0.88617047 0.72953104 0.25841717]
 [0.07307434 0.41609104 0.81347171]
 [0.53782684 0.68834974 0.68264449]
 [0.57827093 0.97768604 0.50589128]
 [0.4967988  0.34469846 0.59174938]]


 c) Agrega una columna de unos al principio de la matriz resultante, obteniendo una matriz de forma (5, 4).

In [41]:
unos = np.ones((5, 1))
matriz_final = np.concatenate((unos, matriz_combinada), axis=1)
print("Matriz final:\n", matriz_final)

Matriz final:
 [[1.         0.88617047 0.72953104 0.25841717]
 [1.         0.07307434 0.41609104 0.81347171]
 [1.         0.53782684 0.68834974 0.68264449]
 [1.         0.57827093 0.97768604 0.50589128]
 [1.         0.4967988  0.34469846 0.59174938]]


d) Reordena las columnas de la matriz para que la columna de unos esté al final.

In [42]:
matriz_reordenada = np.concatenate((matriz_final[:, 1:], matriz_final[:, 0:1]), axis=1)
print("Matriz reordenada:\n", matriz_reordenada)

Matriz reordenada:
 [[0.88617047 0.72953104 0.25841717 1.        ]
 [0.07307434 0.41609104 0.81347171 1.        ]
 [0.53782684 0.68834974 0.68264449 1.        ]
 [0.57827093 0.97768604 0.50589128 1.        ]
 [0.4967988  0.34469846 0.59174938 1.        ]]


PREGUNTA 6:

 a) Crea una matriz simétrica positiva definida de tamaño 3x3.

In [45]:
# Matriz aleatoria 3x3
A = np.random.rand(3, 3)

# Matriz simétrica
A = (A + A.T) / 2

# Matriz positiva con un valor a la diagonal
A += 3 * np.eye(3)

print("Matriz simétrica positiva definida:\n", A)

Matriz simétrica positiva definida:
 [[3.1806572  0.72196224 0.71319893]
 [0.72196224 3.75785119 0.4432643 ]
 [0.71319893 0.4432643  3.32407074]]


 b) Calcula sus valores y vectores propios (eigenvalores y eigenvectores).

In [19]:
eigenvalores, eigenvectores = np.linalg.eig(A)

print("Eigenvalores:\n", eigenvalores)
print("Eigenvectores:\n", eigenvectores)

Eigenvalores:
 [4.0578394  2.97523302 3.3768495 ]
Eigenvectores:
 [[-0.89168528 -0.36985408 -0.26096994]
 [-0.38193893  0.92417534 -0.0047542 ]
 [-0.24294035 -0.09543533  0.96533522]]


c) Verifica que la multiplicación de la matriz original por un vector propio es igual al producto del eigenvalor
 correspondiente por el vector propio.

In [20]:
for i in range(len(eigenvalores)):
    producto_matriz_vector = np.dot(A, eigenvectores[:, i])
    producto_eigenvalor_vector = eigenvalores[i] * eigenvectores[:, i]
    print(f"Para el eigenvalor {eigenvalores[i]}:")
    print("Producto matriz-vector:", producto_matriz_vector)
    print("Producto eigenvalor-vector:", producto_eigenvalor_vector)
    print("Diferencia:", producto_matriz_vector - producto_eigenvalor_vector)
    print("-" * 20)

Para el eigenvalor 4.057839398407642:
Producto matriz-vector: [-3.61831568 -1.54984682 -0.98581291]
Producto eigenvalor-vector: [-3.61831568 -1.54984682 -0.98581291]
Diferencia: [8.88178420e-16 1.77635684e-15 3.33066907e-16]
--------------------
Para el eigenvalor 2.9752330218474685:
Producto matriz-vector: [-1.10040208  2.74963698 -0.28394234]
Producto eigenvalor-vector: [-1.10040208  2.74963698 -0.28394234]
Diferencia: [ 0.00000000e+00 -2.66453526e-15 -1.66533454e-16]
--------------------
Para el eigenvalor 3.376849497273532:
Producto matriz-vector: [-0.88125622 -0.01605422  3.25979175]
Producto eigenvalor-vector: [-0.88125622 -0.01605422  3.25979175]
Diferencia: [-4.44089210e-16 -5.44703171e-16  0.00000000e+00]
--------------------


PREGUNTA 7:

a) Construye un sistema de ecuaciones lineales con tres ecuaciones y tres incógnitas donde la matriz de
 coeficientes es singular (no invertible).

In [46]:
# Sistema de ecuaciones con matriz de coeficientes singular:
# Ecuación 1: x + y + z = 6
# Ecuación 2: 2x + 2y + 2z = 12  (Múltiplo de la ecuación 1)
# Ecuación 3: x + y - z = 2

# Matriz de coeficientes singular (filas linealmente dependientes)
A = np.array([[1, 1, 1],
              [2, 2, 2],
              [1, 1, -1]])

# Vector de términos independientes
b = np.array([6, 12, 2])

print("Matriz de coeficientes A:\n", A)
print("Vector de términos independientes b:\n", b)

# Generará un error ya que la matriz es singular.
# Para demostrar la singularidad se puede calcular el determinante
determinante = np.linalg.det(A)

print("El determinante de A es:",determinante)

# Para mostrar que el sistema no tiene solución única:
# np.linalg.solve(A,b)

Matriz de coeficientes A:
 [[ 1  1  1]
 [ 2  2  2]
 [ 1  1 -1]]
Vector de términos independientes b:
 [ 6 12  2]
El determinante de A es: 0.0


b) Intenta resolver el sistema utilizando np.linalg.solve() y explica el resultado obtenido.

In [47]:
try:
    x = np.linalg.solve(A, b)
    print("Solución del sistema:", x)
except np.linalg.LinAlgError as e:
    print("Error al resolver el sistema:", e)
    print("La matriz de coeficientes es singular (no invertible), por lo que el sistema no tiene una solución única o no tiene solución.")

Error al resolver el sistema: Singular matrix
La matriz de coeficientes es singular (no invertible), por lo que el sistema no tiene una solución única o no tiene solución.


PREGUNTA 8

a) Crea un array de forma (4, 4, 4) con números enteros aleatorios entre 0 y 100.

In [48]:
array_3d = np.random.randint(0, 101, size=(4, 4, 4))
array_3d

array([[[93, 84, 64, 79],
        [93, 31,  4, 46],
        [95, 91, 20, 26],
        [18, 35, 30, 39]],

       [[38, 42, 35, 12],
        [42, 90, 14, 44],
        [ 5, 28, 88, 32],
        [75,  6, 65, 77]],

       [[15, 46, 33, 61],
        [35, 65, 40, 67],
        [74, 90, 43, 61],
        [84, 68, 41, 24]],

       [[13, 39, 48, 29],
        [90, 63, 60, 67],
        [80, 85, 35,  5],
        [31, 67, 20, 15]]])

b) Calcula la suma a lo largo del eje 0, obteniendo un array de forma (4, 4).

In [49]:
suma_eje_0 = np.sum(array_3d, axis=0)
suma_eje_0

array([[159, 211, 180, 181],
       [260, 249, 118, 224],
       [254, 294, 186, 124],
       [208, 176, 156, 155]])

 c) Calcula el promedio a lo largo del eje 1, obteniendo un array de forma (4, 4).

In [50]:
promedio_eje_1 = np.mean(array_3d, axis=1)
promedio_eje_1

array([[74.75, 60.25, 29.5 , 47.5 ],
       [40.  , 41.5 , 50.5 , 41.25],
       [52.  , 67.25, 39.25, 53.25],
       [53.5 , 63.5 , 40.75, 29.  ]])

d) Reestructura el array original en una nueva forma de (8, 8) sin perder datos.

In [51]:
array_8x8 = array_3d.reshape(8, 8)
array_8x8

array([[93, 84, 64, 79, 93, 31,  4, 46],
       [95, 91, 20, 26, 18, 35, 30, 39],
       [38, 42, 35, 12, 42, 90, 14, 44],
       [ 5, 28, 88, 32, 75,  6, 65, 77],
       [15, 46, 33, 61, 35, 65, 40, 67],
       [74, 90, 43, 61, 84, 68, 41, 24],
       [13, 39, 48, 29, 90, 63, 60, 67],
       [80, 85, 35,  5, 31, 67, 20, 15]])